# Generated by Django 4.1.2 on 2023-03-22 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='message',
            field=models.TextField(max_length=600),
        ),
    ]
