# Generated by Django 4.1.2 on 2023-03-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(),
        ),
    ]
