# Generated by Django 4.1.2 on 2023-03-22 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0005_alter_contact_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='contact',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
